# -*- coding: utf-8 -*-
"""lab8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c9cscd6vjCwbpHXpFdzI9nfKTkY3XmVo
"""

import requests
from bs4 import BeautifulSoup

url = "https://www.bbc.com/news"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

articles = soup.find_all("div", class_="gs-c-promo")

for news in articles:
  title = news.find("h3").get_text().strip()
  link = news.find("a")["href"]
  print("title of the article: " , title, "link of the title is " , link)

